public class calc {
    public  Integer result{set;get;}
    public  Integer a{set;get;}
    public  Integer b{set;get;}
    public  Integer c{set;get;}
    public  Integer d{set;get;}
    public  Integer e {set;get;}
    public  Integer f{set;get;}
    public  Integer g{set;get;}
    public  Integer h{set;get;}
    public  Integer i{set;get;}
    public  string  j{set;get;}
    public  string  k{set;get;}
    public  string  l{set;get;}
    
 
                    
                    public  Integer val1() 
                    {
                        a=1; 
                        return a;
                    }
                    public Integer val2() 
                    {
                        b=2;
                         return b;
                    }
                    public Integer val3() 
                    {
                        c=3;
                        return c;
                    }
                    public Integer val4() 
                    {
                        d=4;
                        return d;
                    }
                    public Integer val5() 
                    {
                        e=5;
                        return e;
                    }
                    public Integer val6() 
                    {
                        f=6;
                        return f;
                    }
                    public Integer val7() 
                    {
                        g=7;
                        return g;
                    }
                    public Integer val8() 
                    {
                        h=8;
                        return h;
                    }
                    public Integer val9() 
                    {
                        i=9;
                        return i;
                    }
                    public void add() 
                    {
                        j='+';
                    }
                    public void sub() 
                    {
                        k='-';
                    }
                    public void mul() 
                    {
                        l='*';
                    }
                    
                    
       
    }