public class sum_integer {
    public Set<integer> ravi{set;get;}
    public integer size{set;get;}
    public integer sum {set;get;}
    public sum_integer()
    {
       ravi =new Set<integer>();
        ravi.add(10);
        ravi.add(20);
        ravi.add(30);
        ravi.add(40);
        
        sum=0;
        size=ravi.size();
        for(integer i=0;i<size;i++)
        {
            
            
        }    
		        
    }   
        
        
        
}